
spring:
  rabbitmq:
    username: witenqwp
    password: 4a4iskPOytzEV_B-eULU0Yv7MMXkY7p5
    host: dingo.rmq.cloudamqp.com
    virtual-host: witenqwp

  datasource:
    url: jdbc:sqlite:../producer/db.sqlite
    driver-class-name: org.sqlite.JDBC
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true